version: '3'

services:
  mssql:
    image: mssql:latest
    build: ./sqlserver
    stop_signal: SIGINT
    ports:
      - 1433:1433
    volumes: 
      - ./sqlserver/data:/data
    networks: 
      network:
        aliases: 
          - mssql.network
  redis:
    image: redis:latest
    build: ./redis
    stop_signal: SIGINT
    volumes: 
      - ./redis/data:/data
    ports:
      - 6379:6379
    networks: 
      network:
        aliases: 
          - redis.network

networks:
  network:
    
